
export const GET_CITY_WEATHER_DATA_REQUEST = 'GET_CITY_WEATHER_DATA_REQUEST';
export const GET_CITY_WEATHER_DATA_SUCSESS = 'GET_CITY_WEATHER_DATA_SUCSESS';
export const GET_CITY_WEATHER_DATA_FAIL = 'GET_CITY_WEATHER_DATA_FAIL';

export const CLEAR_CITY_WEATHER_DATA_REQUEST = 'CLEAR_CITY_WEATHER_DATA_REQUEST';